name: Build and Run

on:
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build the project
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install build dependencies
        run: sudo apt-get install -y cmake build-essential

      - name: Create and configure build directory
        run: |
          mkdir -p build
          cmake -S . -B build

      - name: Build project
        run: cmake --build build

  # Job 2: Run example executable
  run_example:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install build dependencies
        run: sudo apt-get install -y cmake build-essential

      - name: Create and configure build directory
        run: |
          mkdir -p build
          cmake -S . -B build

      - name: Build project (reuses cache)
        run: cmake --build build

      - name: Run example executable
        run: |
          cd build
          ./example/uutf_example
        continue-on-error: false

  # Job 3: Run tests with ctest
  test:
    runs-on: ubuntu-latest
    needs: run_example
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install build dependencies
        run: sudo apt-get install -y cmake build-essential

      - name: Create and configure build directory
        run: |
          mkdir -p build
          cmake -S . -B build

      - name: Build project (reuses cache)
        run: cmake --build build

      - name: Run tests with ctest
        run: |
          cd build
          ctest --verbose --test-dir test/
