name: Build and Run

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install build dependencies
        run: sudo apt-get install -y cmake build-essential

      - name: Create build directory
        run: mkdir build && cd build

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ./uutf_example
        continue-on-error: false
